export const USER_REPOSITORY = 'USER_REPOSITORY';

export const CONTENT_REPOSITORY = 'CONTENT_REPOSITORY';

export const HASHTAG_REPOSITORY = 'HASHTAG_REPOSITORY';

export const CONTENT_TO_HASHTAG_REPOSITORY = 'CONTENT_TO_HASHTAG_REPOSITORY';
